# Generated by Django 5.2.4 on 2025-07-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
