# Generated by Django 5.2.4 on 2025-07-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_articles_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='userid',
            field=models.CharField(default=2, max_length=20),
        ),
        migrations.AlterField(
            model_name='articles',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
