# Generated by Django 5.2.4 on 2025-07-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_articles_userid_alter_articles_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='articles',
            name='userid',
            field=models.CharField(max_length=20),
        ),
    ]
