# Generated by Django 5.2.4 on 2025-07-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_articles_status_alter_articles_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(),
        ),
    ]
