# Generated by Django 5.2.4 on 2025-07-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_articles_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='id',
            field=models.TextField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.TextField(),
        ),
    ]
